server:
  port: 9030

spring:
  application:
    name: GATEWAY-SERVICE
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:9050
  cloud:
    config:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9040/eureka/